module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "surface-tint": "#a3a6ff",
              "secondary": "#c180ff",
              "tertiary-container": "#ff8ed2",
              "surface": "#070d1f",
              "primary-container": "#9396ff",
              "surface-container": "#11192e",
              "error-container": "#a70138",
              "secondary-fixed": "#e5c6ff",
              "on-secondary-fixed": "#4f0089",
              "surface-dim": "#070d1f",
              "error": "#ff6e84",
              "secondary-fixed-dim": "#dbb4ff",
              "surface-container-highest": "#1c253e",
              "on-background": "#dfe4fe",
              "primary-fixed": "#9396ff",
              "tertiary-fixed-dim": "#ef81c4",
              "on-secondary": "#33005b",
              "on-primary-fixed-variant": "#0e009d",
              "surface-container-lowest": "#000000",
              "on-tertiary": "#701455",
              "on-primary-fixed": "#000000",
              "on-secondary-fixed-variant": "#7511c3",
              "on-error": "#490013",
              "on-tertiary-container": "#63054a",
              "inverse-surface": "#faf8ff",
              "inverse-on-surface": "#4f5469",
              "primary-fixed-dim": "#8387ff",
              "primary-dim": "#6063ee",
              "inverse-primary": "#494bd7",
              "error-dim": "#d73357",
              "tertiary-fixed": "#ff8ed2",
              "tertiary-dim": "#ef81c4",
              "outline-variant": "#41475b",
              "on-tertiary-fixed-variant": "#6e1354",
              "background": "#070d1f",
              "on-tertiary-fixed": "#3b002b",
              "outline": "#6f758b",
              "surface-container-high": "#171f36",
              "on-surface": "#dfe4fe",
              "secondary-container": "#6f00be",
              "tertiary": "#ffa5d9",
              "secondary-dim": "#9c48ea",
              "surface-variant": "#1c253e",
              "on-error-container": "#ffb2b9",
              "on-primary": "#0f00a4",
              "surface-container-low": "#0c1326",
              "primary": "#a3a6ff",
              "on-secondary-container": "#e9cdff",
              "surface-bright": "#222b47",
              "on-surface-variant": "#a5aac2",
              "on-primary-container": "#0a0081"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "fontFamily": {
              "headline": ["Space Grotesk"],
              "body": ["Manrope"],
              "label": ["Manrope"]
      }
    },
  },
  plugins: [],
}